/*
 * Copyright (c) 2022 Tomoyuki Sakurai <y@trombik.org>
 * Copyright (c) 2023 Tobias Schramm <t.schramm@t-sys.eu>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *  list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this
 *  list of conditions and the following disclaimer in the documentation and/or
 *  other materials provided with the distribution.
 *
 * 3. Neither the name of "Floorsense Ltd", "Agile Workspace Ltd" nor the names of
 *  its contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
#if !defined(__ESP_WIREGUARD__H__)
#define __ESP_WIREGUARD__H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
#include <esp_err.h>
#include <lwip/netif.h>

//#include "wireguard.h"

#define ESP_WIREGUARD_CONFIG_DEFAULT() { \
    .private_key = NULL, \
    .listen_port = 0, \
    .fw_mark = 0, \
    .bind_netif = NULL, \
    .local_ip = NULL, \
    .local_ip_mask = NULL, \
    .gateway_ip = NULL, \
}

#define ESP_WIREGUARD_PEER_CONFIG_DEFAULT() { \
    .public_key = NULL, \
    .preshared_key = NULL, \
    .allowed_ip = NULL, \
    .allowed_ip_mask = NULL, \
    .endpoint = NULL, \
    .port = 51820, \
    .persistent_keepalive = 0, \
}

#define ESP_WIREGUARD_P2P_CONFIG_DEFAULT() { \
    .local = ESP_WIREGUARD_CONFIG_DEFAULT(), \
    .peer = ESP_WIREGUARD_PEER_CONFIG_DEFAULT(), \
}

typedef struct esp_wireguard_config {
    /* interface config */
    const char* private_key;          /**< a base64 private key generated by wg genkey. Required. */
    int         listen_port;          /**< a 16-bit port for listening */
    uint32_t    fw_mark;              /**< a 32-bit fwmark for outgoing packets */
    const char* bind_netif;           /**< name of the interface to bind to. */
    const char* local_ip;             /**< local ip address */
    const char* local_ip_mask;        /**< subnet mask of local ip address. */
    const char* gateway_ip;           /**< gateway address. */
} esp_wireguard_config_t;

typedef struct esp_wireguard_peer_config {
    const char* public_key;           /**< a base64 public key calculated by wg pubkey from a private key. Required. */
    const char* preshared_key;        /**< a base64 preshared key generated by wg genpsk. */
    const char* allowed_ip;           /**< permitted peer IP network. */
    const char* allowed_ip_mask;      /**< subnet mask of permitted peer IP network. */
    const char* endpoint;             /**< an endpoint IP address or hostname. */
    int         port;                 /**< a port number of remote endpoint. Default is 51820. */
    int         persistent_keepalive; /**< a seconds interval, between 1 and 65535 inclusive, of how often to send an
                                           authenticated empty packet to the peer for the purpose of keeping a stateful
                                           firewall or NAT mapping valid persistently. Set zero to disable the feature.
                                           Default is zero. */
} esp_wireguard_peer_config_t;

typedef struct esp_wireguard {
//	struct wireguard_device	dev;
    struct netif			netif;         /**< storage for the netif */
    struct netif*			netif_default; /**< a pointer to the default netif. */
} esp_wireguard_t;

typedef struct esp_wireguard_p2p_config {
	esp_wireguard_config_t      local;
	esp_wireguard_peer_config_t peer;
} esp_wireguard_p2p_config_t;

typedef struct esp_wireguard_p2p {
	esp_wireguard_t wg;
	uint8_t peer_index;
	bool peer_added;
	bool peer_connected;
} esp_wireguard_p2p_t;

/**
 * @brief Initialize WireGuard
 *
 * Call this function to initilize the context of WireGuard.
 *
 * Do not call this function multiple times.
 *
 * To connect to other peer, use `esp_wireguard_disconnect()`, and
 * `esp_wireguard_init()` with a new configuration.
 *
 * @param       config WireGuard configuration.
 * @param[out]  ctx Context of WireGuard.
 *
 * @return
 *      - ESP_OK: Successfully initilized WireGuard interface.
 *      - ESP_ERR_INVALID_ARG: given argument is invalid.
 *      - ESP_FAIL: Other error.
 */
esp_err_t esp_wireguard_init(const esp_wireguard_config_t *config, esp_wireguard_t *wg);
esp_err_t esp_wireguard_p2p_init(const esp_wireguard_p2p_config_t *config, esp_wireguard_p2p_t *wg);

/**
 * @brief Create a WireGuard interface and start establishing the connection
 *        to the peer.
 *
 * Call the funtion to start establishing the connection. Note that `ESP_OK`
 * does not mean the connection is established. To see if the connection is
 * established, or the peer is up, use `esp_wireguardif_peer_is_up()`.
 *
 * Do not call this function multiple times.
 *
 * @param       ctx Context of WireGuard.
 * @return
 *      - ESP_OK on success.
 *      - ESP_FAIL on failure.
 */
esp_err_t esp_wireguard_add_peer(const esp_wireguard_peer_config_t *config, esp_wireguard_t *wg, uint8_t *out_peer_index);
esp_err_t esp_wireguard_connect_peer(esp_wireguard_t *wg, uint8_t peer_index);
esp_err_t esp_wireguard_p2p_connect(const esp_wireguard_p2p_config_t *config, esp_wireguard_p2p_t *wg);

/**
 * @brief Set the default gateway to the peer.
 * @param ctx Context of WireGuard
 * @return
 *      - ESP_OK on success.
 */
esp_err_t esp_wireguard_set_default(esp_wireguard_t *wg);
esp_err_t esp_wireguard_p2p_set_default(esp_wireguard_p2p_t *wg);

/**
 * @brief Test if the peer is up.
 */
esp_err_t esp_wireguard_peer_is_up(esp_wireguard_t *wg, uint8_t peer_index);
esp_err_t esp_wireguard_p2p_is_up(esp_wireguard_p2p_t *wg);

/**
 * @brief Disconnect from the peer
 *
 * @param ctx Context of WireGuard.
 * @return
 *      - ESP_OK on success.
 */
esp_err_t esp_wireguard_disconnect(esp_wireguard_t *wg);
esp_err_t esp_wireguard_disconnect_peer(esp_wireguard_t *wg, uint8_t peer_index);
esp_err_t esp_wireguard_remove_peer(esp_wireguard_t *wg, uint8_t peer_index);
esp_err_t esp_wireguard_p2p_disconnect(esp_wireguard_p2p_t *wg);
esp_err_t esp_wireguard_p2p_free(esp_wireguard_p2p_t *wg);

#ifdef __cplusplus
}
#endif

#endif
// vim: expandtab
